#!/bin/bash

selected=$(
    rofi -dmenu -i -l 10 <<EOF
Lock
Logout
Suspend
Reboot
Shutdown
EOF
)

selected=$(echo "$selected" | awk '{print tolower($1)}' | tr -d '[:space:]')

case "$selected" in
lock)
    exec ~/.local/bin/lock
    ;;
logout)
    swaymsg exit
    ;;
suspend)
    exec systemctl suspend
    ;;
reboot)
    exec systemctl reboot
    ;;
shutdown)
    exec systemctl poweroff -i
    ;;
*)
    echo "unknown selection: $selected"
    ;;
esac
