#!/bin/bash

cat <<ENDOFLICENSE >/dev/null
Retrieved from https://github.com/davatorium/rofi-scripts/tree/master/rofi-finder

Copyright 2017 Viktor Jacynycz<viktor@jacynycz.es>

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
ENDOFLICENSE

show_help() {
    echo "!!-- Type your search query to find files"
    echo "!!-- To seach again type !<search_query>"
    echo "!!-- To seach parent directories type ?<search_query>"
    echo "!!-- You can print this help by typing !!"
}

#USE: rofi  -show find -modi find:/usr/local/libexec/rofi/finder
if [ ! -z "$@" ]; then
    QUERY=$@
    if [[ "$@" == /* ]]; then
        if [[ "$@" == *\?\? ]]; then
            coproc (xdg-open "${QUERY%\/* \?\?}" >/dev/null 2>&1)
            exec 1>&-
            exit
        else
            coproc (xdg-open "$@" >/dev/null 2>&1)
            exec 1>&-
            exit
        fi
    elif [[ "$@" == \!\!* ]]; then
        show_help
    elif [[ "$@" == \?* ]]; then
        while read -r line; do
            echo "$line" \?\?
        done <<<$(find ~ -type d -path '*/\.*' -prune -o -not -name '.*' -type f -iname *"${QUERY#\?}"* -print)
    else
        find ~ -type d -path '*/\.*' -prune -o -not -name '.*' -type f -iname *"${QUERY#!}"* -print
    fi
else
    show_help
fi
