#!/bin/bash
set -xeuo pipefail
# This script copies the manifests from the current directory
# into their installed location.
manifestdir=/usr/share/doc/bootc-base-imagectl/manifests
mkdir -p "$manifestdir/"
cp -a manifests $manifestdir/
cp -a fedora-bootc.yaml $manifestdir/
# Set the default
ln -s fedora-bootc.yaml $manifestdir/default.yaml
# And embed the rebuild script
install -m 0755 -t /usr/libexec ./bootc-base-imagectl
