packages:
  - adobe-source-code-pro-fonts
  - alacritty
  - fontawesome-fonts-all
  - grim
  - mako
  - materia-gtk-theme
  - nautilus
  - network-manager-applet
  - nm-connection-editor-desktop
  - paper-icon-theme
  - playerctl
  - powerline-fonts
  - python3-requests
  - rofi
  - slurp
  - sway
  - sway-systemd
  - swaybg
  - swayidle
  - swaylock
  - virt-manager
  - virt-viewer
  - waybar
  - wf-recorder
  - wl-clipboard
  - blueman
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk
  - fprintd-pam
  - kanshi
  - plymouth-system-theme
  - lxqt-policykit
  - wev
  - wlr-randr
  - bolt
  - colord
  - gutenprint
  - uresourced
  - dbus-daemon

include:
  - gui-apps.yaml
  - gui-audio.yaml
  - gui-games.yaml
  - gui-media.yaml
  - redhat.yaml

exclude-packages:
  # I don't want GDM
  - gdm
